services:
  pool-app:
    build: .
    network_mode: "host" # todo!
    environment:
      - NODE_ENV=production
      - OAUTH2_AUTH_SERVER=https://account.sjallabong.eu
      - OAUTH2_CLIENT_ID=sjallabong-pool
      - APP_BASE_URL=https://pool.sjallabong.eu
      - SESSION_SECRET=asdfadsfadsfasd
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - data:/app

volumes:
  data:
